### ISSUE TITLE
CTRL+Z browser conflict

### ISSUE THREAD

**Issue by lavgup** [nimeshnayaju/tldrawe#2]
Great extension, thanks for building this.

However, when using the CTRL+Z shortcut to undo a tldraw action, it also runs the browser shortcut that opens the most recently deleted tab. I was wondering whether you'd be able to disable the browser shortcut that coincides with CTRL+Z (in my case opening the tab) when a tldrawe session is active, so only the action is undone.

Thanks.

**Comment by nimeshnayaju** [comment]
Hi, sorry for being late to respond. I don't plan to make any further updates to this extension, at least for the time being. Besides, tldraw v2 was recently released with a major rewrite, and since this extension is based on the V1 implementation, I am not sure if it makes sense to continue developing the extension. I may rewrite the extension from scratch either based on tldraw v2 or my own canvas implementation, but that won't be for a while.
